### ISSUE TITLE
feature request: option to print the ID of the target window

### ISSUE THREAD

**Issue by ikn** [ntrrgc/right-window#2]
This is would be much more flexible - seems better than implementing a load of possible actions (even the inclusion of swap seems a bit much).

**Comment by ntrrgc** [comment]
Actually this is already implemented! I just thought it was too specific to put in the README.

From `right-window-bspwm --help`:

```
   -g,  --get-id
     (OR required)  Print the identifier of the found window.
```

Example of usage:

```
ntrrgc@madoka❯ ./right-window-bspwm -g right
31457340
ntrrgc@madoka❯ bspc node -f 31457340
```
