### ISSUE TITLE
The format of `bspc wm --dump` changed

### ISSUE THREAD

**Issue by baskerville** [ntrrgc/right-window#3]
I've noticed that `bspwm/bspwm.cc` relies on: `focused{Monitor,Desktop}Name`. Those keys no longer exist and were replaced with `focused{Monitor,Desktop}Id`.

**Comment by ntrrgc** [comment]
Thanks for the notice! I will update it shortly.

**Comment by ntrrgc** [comment]
It may take a bit longer since I just updated bspwm and it has broken basic stuff like being able to focus windows by clicking them.

**Comment by baskerville** [comment]
Remove all the lines in your `sxhkdrc` that refer to the _pointer_ domain. And set `click_to_focus` to _true_.

**Comment by ntrrgc** [comment]
Thank you. It's working now again.
