### ISSUE TITLE
Add ability to run make install, to well... install

### ISSUE THREAD

**Issue by CamilleScholtz** [ntrrgc/right-window#5]

**Comment by ntrrgc** [comment]
Who ever does that? :smile:

**Comment by ntrrgc** [comment]
I will look into it.

**Comment by CamilleScholtz** [comment]
for example, Arch PKGBUILDs, CRUX Pkgfiles, Void package templates, Alpine package templates all often use a make install in there build instructions whenever possible. I create quite a lot of packages and almost never come across a Makefile without an install instruction.

EDIT: Thank you :)

**Comment by ntrrgc** [comment]
I was joking obviously. I don't like running `make install` outside of a package generation script though.
